version: "3.8"

services:
    backend:
        build:
            context: ./src/backend/
            dockerfile: backend.Dockerfile
        volumes:
            - ./src/backend:/usr/src/app
        ports:
            - 5000:5000
        env_file:
            - ./src/backend/.env
        depends_on:
            - db
    db:
        image: postgres:13-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=testpass
            - POSTGRES_DB=chimarathontest

    frontend:
        build:
            context: ./src/frontend/
            dockerfile: frontend.Dockerfile
        command: ["npm", "start"]
        volumes:
            - ./src/frontend:/frontend
            - node-modules:/frontend/node_modules
        environment:
            - NODE_ENV=development
        ports:
            - "3000:3000"
        depends_on:
            - backend

volumes:
    postgres_data:
    node-modules:
